trigger: none

name: Deploy Bicep files

variables:
  - group: PipeLib
  - name: templateFile
    value: "Provisioning/Bicep/main.bicep"
  - name: paramFile
    value: Provisioning/Bicep/parameters.bicepparam
  - template: vars.yml

pool:
  name: Default

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: $(azureServiceConnection)
      scriptType: bash
      scriptLocation: inlineScript
      useGlobalConfig: true
      inlineScript: |
        az --version
        az group create --name ${{variables.name}}-rg --location $(location)
        az stack group create \
          --name ${{variables.name}}-stack \
          --resource-group ${{variables.name}}-rg \
          --template-file $(templateFile) \
          --parameters $(paramFile) \
          --deny-settings-mode none \
          --delete-resources \
          --delete-resource-groups
