trigger: none

name: Deploy Bicep files

variables:
  - group: PipeLib
  - name: templateFile
    value: "Provisioning/Bicep/main.bicep"
  - name: paramFile
    value: Provisioning/Bicep/parameters.bicepparam
  - template: vars.yml

pool:
  name: Default

steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: "specific"
      project: "20f0806b-559a-4239-a454-cc8b67b627c8"
      definition: "1"
      buildVersionToDownload: "latest"
      targetPath: "$(Pipeline.Workspace)"
  - task: AzureCLI@2
    inputs:
      azureSubscription: $(azureServiceConnection)
      scriptType: bash
      scriptLocation: inlineScript
      useGlobalConfig: true
      inlineScript: |
        az --version
        az group create --name ${{variables.name}}-rg --location $(location)
        az stack group create \
          --name ${{variables.name}}-stack \
          --resource-group ${{variables.name}}-rg \
          --template-file $(templateFile) \
          --parameters $(paramFile) \
          --deny-settings-mode none \
          --delete-resources \
          --delete-resource-groups
